config/routes.rb
Rails.application.routes.draw do
  

  resources :songs
  
  root "pages#home"
  
get "/rock" => "pages#rock"  

get "/pop" => "pages#pop"

get "/hiphop" => "pages#hiphop"

get "poprock" => "pages#poprock"

get "classical" => "pages#classical"

get "kpop" => "pages#kpop"

get "rap" => "pages#rap"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song.rb
class Song < ApplicationRecord
    validates :title, presence: true
    validates :artist, presence: true
    validates :genre, presence: true
    validates :link, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @songs = Song.all.reverse_order
    @latest_songs = @songs.last(5)
  end

def rock
  @rock_songs = Song.all.where(genre: "rock")
  end
  
  def pop
  @pop_songs = Song.all.where(genre: "pop")
  end
  
  def hiphop
  @hiphop_songs = Song.all.where(genre: "hiphop")
  end
  
  def poprock
  @poprock_songs = Song.all.where(genre: "poprock")
  end
  
  def classical
  @classical_songs = Song.all.where(genre: "classical")
  end
  
  def kpop
  @kpop_songs = Song.all.where(genre: "kpop")
  end
  
  def rap
  @rap_songs = Song.all.where(genre: "rap")
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all.reverse_order
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:artist, :title, :genre, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mitch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<style>

    body, html {
    height: cover;
}

body { 
    background-image: url("https://i.ytimg.com/vi/42dVcSGdSgw/maxresdefault.jpg");

    height: cover; 

   
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
  }
</style>
  <body>
    
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Mitch", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "post new song", new_song_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Genres <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="pop">Pop</a></li>
            <li><a href="rock">Rock</a></li>
            <li><a href="poprock">Poprock</a></li>
            <li><a href="rap">Rap</a></li>
            <li><a href="hiphop">Hiphop</a></li>
            <li><a href="classical">Classical</a></li>
            <li><a href="kpop">Kpop</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
   
   <div class="container"> 
    <%= yield %>
    </div>
    
  </body>
</html>

app/views/pages/classical.html.erb
<p id="notice"><%= notice %></p>
<center>
<h1>classical songs</h1>

<h4>post and share your favorite music!</h4>
<br>
<div class="list-group" style="max-width: 600px">
  <% @classical_songs.each do |song| %>
    <%= link_to "#{song.title} - #{song.artist}", song, class: "list-group-item" %>
  <% end %>
</div>
</center>

app/views/pages/hiphop.html.erb
<p id="notice"><%= notice %></p>
<center>
<h1>Hiphop songs</h1>

<h4>post and share your favorite music!</h4>
<br>
<div class="list-group" style="max-width: 600px">
  <% @hiphop_songs.each do |song| %>
    <%= link_to "#{song.title} - #{song.artist}", song, class: "list-group-item" %>
  <% end %>
</div>
</center>

app/views/pages/home.html.erb
<center>
<div class="page-header" style="max-width: 400px">
    <h1> <font size=7 color="#080228"> Mitch <br><small><font color="#080228">post and share great music</small></font></font></h1><br>
    <%= link_to "new song", new_song_path, class: "btn btn-primary btn-lg"%>
</div>


<h4> <font color="#fff">Latest songs</font></h4>
<br>
<div class="list-group" style="max-width: 600px">
  <% @latest_songs.each do |song| %> 
    <%= link_to "#{song.title} - #{song.artist}", song, class: "list-group-item" %>
  <% end %>
</div>
</center>

app/views/pages/kpop.html.erb
<p id="notice"><%= notice %></p>
<center>
<h1>Kpop songs</h1>

<h4>post and share your favorite music!</h4>
<br>
<div class="list-group" style="max-width: 600px">
  <% @kpop_songs.each do |song| %>
    <%= link_to "#{song.title} - #{song.artist}", song, class: "list-group-item" %>
  <% end %>
</div>
</center>

app/views/pages/pop.html.erb
<p id="notice"><%= notice %></p>
<center>
<h1>Pop songs</h1>

<h4>post and share your favorite music!</h4>
<br>
<div class="list-group" style="max-width: 600px">
  <% @pop_songs.each do |song| %>
    <%= link_to "#{song.title} - #{song.artist}", song, class: "list-group-item" %>
  <% end %>
</div>
</center>

app/views/pages/poprock.html.erb
<p id="notice"><%= notice %></p>
<center>
<h1>Poprock songs</h1>

<h4>post and share your favorite music!</h4>
<br>
<div class="list-group" style="max-width: 600px">
  <% @poprock_songs.each do |song| %>
    <%= link_to "#{song.title} - #{song.artist}", song, class: "list-group-item" %>
  <% end %>
</div>
</center>

app/views/pages/rap.html.erb
<p id="notice"><%= notice %></p>
<center>
<h1>Rap songs</h1>

<h4>post and share your favorite music!</h4>
<br>
<div class="list-group" style="max-width: 600px">
  <% @rap_songs.each do |song| %>
    <%= link_to "#{song.title} - #{song.artist}", song, class: "list-group-item" %>
  <% end %>
</div>
</center>

app/views/pages/rock.html.erb
<p id="notice"><%= notice %></p>
<center>
<h1>Rock songs</h1>

<h4>post and share your favorite music!</h4>
<br>
<div class="list-group" style="max-width: 600px">
  <% @rock_songs.each do |song| %>
    <%= link_to "#{song.title} - #{song.artist}", song, class: "list-group-item" %>
  <% end %>
</div>
</center>

app/views/songs/_form.html.erb
<%= form_with(model: song, local: true) do |form| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group" style="max-width: 400px">
    <h5>artist</h5>
    <%= form.text_field :artist, class: "form-control input-lg" %>
  </div>

  <div class="form-group" style="max-width:400px">
    <h5>title</h5>
    <%= form.text_field :title, class: "form-control input-lg" %>
  </div>

  <div class="form-group" style="max-width: 400px">
    <h5>genre</h5>
    <%= form.select :genre, [
                            ["pop", "pop"],
                            ["hiphop", "hiphop"],
                            ["rap", "rap"],
                            ["poprock", "poprock"],
                            ["classical", "classical"],
                            ["kpop", "kpop"]
                            ], prompt: "select genre...", id: :song_genre %>
  </div>

  <div class="form-group" style="max-width: 400px">
    <h5>Youtube ID (example: ztIEogFr9j4)</h5>
    <%= form.text_field :link, class: "form-control input-lg" %>
  </div>

   <div class="form-group">
    <%= form.submit 'Post Song', class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mitch</h1>

<h4>post and share your favorite music!</h4>
<br>
<div class="list-group" style="max-width: 600px">
  <% @songs.each do |song| %>
    <%= link_to "#{song.title} - #{song.artist}", song, class: "list-group-item" %>
  <% end %>
</div>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <h3><%= @song.title %> - <%= @song.artist %> (<%= @song.genre %>)</h3>
  <div class="container">
    <iframe src="//www.youtube.com/embed/<%= @song.link %>" 
    frameborder="0" allowfullscreen class="video"></iframe>
  </div>
</div>